name: Build and Publish NuGet

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'NuGet Package Version (Optional - specify only for manual trigger)'
        required: false
        default: ''

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Determine Version
        id: set_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.packageVersion }}" ]; then
          echo "VERSION=${{ github.event.inputs.packageVersion }}"
          else
          echo "VERSION=$(echo ${{ github.event.release.tag_name }} | cut -c 2-)"
          fi
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Pack
        run: dotnet pack ./src/X.Serilog.Sinks.Telegram/X.Serilog.Sinks.Telegram.csproj --configuration Release --no-build --output nupkgs /p:PackageVersion=${{ env.RELEASE_VERSION }}

      - name: Push to NuGet
        run: dotnet nuget push "nupkgs/**/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
